version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: discord_bot
      DB_USER: bot_user
      DB_PASSWORD: bot_password
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: discord_bot
      MYSQL_USER: bot_user
      MYSQL_PASSWORD: bot_password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mariadb_data:

networks:
  bot-network:
    driver: bridge